# vim:ft=kitty

## name: oxide
## author: jakmaz
## license: MIT
## upstream: https://github.com/oxidescheme/kitty/blob/main/oxide.conf
## blurb: A minimalist colorscheme for kitty.

#: The basic colors

foreground #cecece
background #161616
selection_foreground #cecece
selection_background #262626

#: Cursor colors

cursor #cecece
cursor_text_color #161616
cursor_trail_color none

#: URL underline color when hovering with mouse

url_color #bebebe

#: kitty window border colors and terminal bell colors

active_border_color #cecece
inactive_border_color #555555
bell_border_color #ed756e
visual_bell_color none

#: OS Window titlebar colors

wayland_titlebar_color system
macos_titlebar_color system

#: Tab bar colors

active_tab_foreground #cecece
active_tab_background #222222
inactive_tab_foreground #8f8f8f
inactive_tab_background #161616
tab_bar_background none
tab_bar_margin_color none

#: Colors for marks (marked text in the terminal)

mark1_foreground #161616
mark1_background #7bd77f
mark2_foreground #161616
mark2_background #ff9890
mark3_foreground #161616
mark3_background #b5b2ff

#: The basic 16 colors

#: black
color0 #262626
color8 #8f8f8f

#: red
color1 #ed756e
color9 #ff9890

#: green
color2 #5bb661
color10 #7bd77f

#: yellow
color3 #c39900
color11 #e3b831

#: blue
color4 #3ba6f5
color12 #6fc6ff

#: magenta
color5 #968ff7
color13 #b5b2ff

#: cyan
color6 #00baaa
color14 #00dcca

#: white
color7 #cecece
color15 #dedede
